# Generated by Django 2.2.3 on 2019-07-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0003_auto_20190717_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque_Consommable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Marque', models.CharField(max_length=250)),
                ('Pays', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Marques des Consommable',
            },
        ),
        migrations.CreateModel(
            name='Model_Consommable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Model', models.CharField(max_length=250)),
                ('Annee', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Models des Consommable',
            },
        ),
        migrations.CreateModel(
            name='Type_Consommable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Type', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Types des Consommable',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='Marque_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magasin.Marque_Consommable'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Model_Article_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Magasin.Model_Consommable'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Type_Article_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magasin.Type_Consommable'),
        ),
    ]
