# Generated by Django 2.1.2 on 2019-07-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0006_auto_20190718_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Date_C11',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Date_C5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Date_C7',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Num_C11',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Num_C5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Num_C7',
        ),
    ]
