# Generated by Django 2.1.2 on 2018-11-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Architecture', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Categorie', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Date_Panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Etat', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Fonction', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Grade', models.CharField(default='', max_length=250)),
                ('Designation_Grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Marque', models.CharField(max_length=250)),
                ('Pays', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Serie', models.CharField(max_length=250)),
                ('Address_Mac', models.CharField(max_length=30)),
                ('Caracteristiques', models.CharField(default='', max_length=250)),
                ('Description', models.CharField(default='', max_length=250)),
                ('Designation_Materiel', models.CharField(max_length=250)),
                ('Address_Ip', models.CharField(default='0.0.0.0', max_length=15)),
                ('Passerelle', models.CharField(default='0.0.0.0', max_length=15)),
                ('Masque', models.CharField(default='0.0.0.0', max_length=15)),
                ('Quantite', models.IntegerField(default=0)),
                ('Categorie_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Categorie')),
                ('Etat_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Etat')),
                ('Marque_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Matr_Panne_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Panne_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Date_Panne')),
                ('Materiel_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Model', models.CharField(max_length=250)),
                ('Annee', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Panne', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule_Personne', models.CharField(max_length=15)),
                ('Nom', models.CharField(max_length=250)),
                ('Prenom', models.CharField(max_length=250)),
                ('Fonction_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Fonction')),
                ('Grade_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Service', models.CharField(default='', max_length=250)),
                ('Designation_Service', models.CharField(max_length=10)),
                ('Service_Per', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Equipement.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Systeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Systeme', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('Architecture_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Architecture')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='personne',
            name='Service_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Service'),
        ),
        migrations.AddField(
            model_name='panne',
            name='Type_Panne_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Type_Panne'),
        ),
        migrations.AddField(
            model_name='matr_panne_date',
            name='Panne_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Panne'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='Model_Materiel_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Model_Materiel'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='Service_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Service'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='Systeme_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Systeme'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='Type_Materiel_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipement.Type_Materiel'),
        ),
    ]
