# Generated by Django 2.1.2 on 2018-11-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Service_Per',
        ),
    ]
