# Generated by Django 2.1.2 on 2018-11-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0002_remove_service_service_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Service_Per',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Equipement.Service'),
        ),
    ]
