# Generated by Django 2.1.2 on 2018-12-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0005_auto_20181201_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='Designation_Materiel',
        ),
    ]
