# Generated by Django 2.1.2 on 2018-12-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0006_remove_materiel_designation_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='Pays',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Caracteristiques',
            field=models.CharField(default='/', max_length=250),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Description',
            field=models.CharField(default='/', max_length=250),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Model_Materiel_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipement.Model_Materiel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Systeme_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipement.Systeme'),
        ),
    ]
