# Generated by Django 2.1.2 on 2018-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0007_auto_20181201_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='Quantite',
            field=models.IntegerField(default=1),
        ),
    ]
