# Generated by Django 2.1.2 on 2018-12-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0008_auto_20181201_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Kit', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='Kit_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipement.Kit'),
        ),
    ]
