# Generated by Django 2.1.2 on 2018-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0010_auto_20181228_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc_matr',
            name='Document_FK',
        ),
        migrations.RemoveField(
            model_name='doc_matr',
            name='Materiel_FK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='Type_Doc_FK',
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Address_Ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Address_Mac',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Masque',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Num_Serie',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Passerelle',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Doc_Matr',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Type_Document',
        ),
    ]
