# Generated by Django 2.1.2 on 2019-07-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0012_auto_20181228_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architecture',
            options={'verbose_name_plural': 'Architectures'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='date_panne',
            options={'verbose_name_plural': 'Dates des Pannes'},
        ),
        migrations.AlterModelOptions(
            name='doc_matr',
            options={'verbose_name_plural': 'documents des materiels'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='etat',
            options={'verbose_name_plural': 'Etat des Equipements'},
        ),
        migrations.AlterModelOptions(
            name='fonction',
            options={'verbose_name_plural': 'Fonctions'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'verbose_name_plural': 'Liste des Kits'},
        ),
        migrations.AlterModelOptions(
            name='marque',
            options={'verbose_name_plural': 'Marques'},
        ),
        migrations.AlterModelOptions(
            name='materiel',
            options={'verbose_name_plural': 'Materiels'},
        ),
        migrations.AlterModelOptions(
            name='matr_panne_date',
            options={'verbose_name_plural': 'Materiel Date Panne'},
        ),
        migrations.AlterModelOptions(
            name='model_materiel',
            options={'verbose_name_plural': 'Models des Equipements'},
        ),
        migrations.AlterModelOptions(
            name='panne',
            options={'verbose_name_plural': 'Pannes'},
        ),
        migrations.AlterModelOptions(
            name='personne',
            options={'verbose_name_plural': 'Personnes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='systeme',
            options={'verbose_name_plural': 'Systemes'},
        ),
        migrations.AlterModelOptions(
            name='type_document',
            options={'verbose_name_plural': 'Types des Documents'},
        ),
        migrations.AlterModelOptions(
            name='type_materiel',
            options={'verbose_name_plural': 'Types des Equipements'},
        ),
        migrations.AlterModelOptions(
            name='type_panne',
            options={'verbose_name_plural': 'Types des Pannes'},
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='Address_Ip',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='Masque',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='Passerelle',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='Quantite',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='Systeme_FK',
        ),
    ]
