# Generated by Django 2.1.2 on 2019-07-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0013_auto_20190717_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='Categorie_FK',
        ),
    ]
