# Generated by Django 2.1.2 on 2019-07-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0015_auto_20190717_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='Address_Mac',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
