# Generated by Django 2.2.3 on 2019-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipement', '0017_auto_20190718_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='Date_C11',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='Date_C5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='Date_OrdM',
            field=models.DateField(blank=True, null=True),
        ),
    ]
