# Generated by Django 2.1.2 on 2018-12-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='armoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=250)),
                ('n_serie', models.CharField(default='', max_length=250)),
                ('ip', models.CharField(default='', max_length=250)),
                ('mac', models.CharField(default='', max_length=250)),
                ('version', models.CharField(default='', max_length=250)),
                ('anne', models.CharField(default='', max_length=250)),
                ('software', models.CharField(default='', max_length=250)),
                ('armoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.armoire')),
            ],
        ),
        migrations.CreateModel(
            name='etat_equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='type_arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='type_equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='etat_equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.etat_equipement'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='type_equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.type_equipement'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.usage'),
        ),
        migrations.AddField(
            model_name='armoire',
            name='type_armoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.type_arm'),
        ),
    ]
