# Generated by Django 2.1.2 on 2018-12-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reseaux', '0002_auto_20181227_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='etat_equipement',
        ),
    ]
