# Generated by Django 2.1.2 on 2019-07-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reseaux', '0008_auto_20181228_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armoire',
            options={'verbose_name_plural': 'Armoires'},
        ),
        migrations.AlterModelOptions(
            name='equipement',
            options={'verbose_name_plural': 'Equipements'},
        ),
        migrations.AlterModelOptions(
            name='type_arm',
            options={'verbose_name_plural': 'Types des armoires'},
        ),
        migrations.AlterModelOptions(
            name='type_equipement',
            options={'verbose_name_plural': 'Types des equipements'},
        ),
        migrations.AlterModelOptions(
            name='usage',
            options={'verbose_name_plural': 'Usages'},
        ),
        migrations.AlterField(
            model_name='armoire',
            name='type_armoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.Type_arm'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='armoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.Armoire'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type_equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.Type_equipement'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reseaux.Usage'),
        ),
    ]
